# Basic
title: guanchun.yu
subtitle: åšä¸€ä¸ªæœ‰èŠ‚åˆ¶çš„äººï¼
welcome_message: æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢
description: å·¥ä½œä¸€å¹´å¤šçš„ç¨‹åºå‘˜, ç°å°±èŒäºæ­å·è´è´ç½‘, è„±å‘æ˜¯ä¸å¯èƒ½è„±çš„ğŸ™‚
creator: <a href="http://xiaoyuervae.com">@xiaoyuervae</a>

url: "http://xiaoyuervae.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: åšå®¢
    description: æŸ¥çœ‹xiaoyuervaeçš„åšå®¢

# Navigation buttons in the front page.
nav:
    - {title: å…³äº, description: è¿›å‡»çš„ç¨‹åºå‘˜, url: 'http://github.com/xiaoyuervae'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: xiaoyuervae
    # duoshuo:

# Social
social:
    weibo: 18667048220
    github: xiaoyuervae
    twitter: xiaoyuervae
#    gplus: 107108267983477358170
    mail: xiaoyuervae@icloud.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# set encoding
encoding: utf-8
